// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.CritterStack.Screenplay.given;

public class a_dot_net_method_identity_application : Specification
{
    const string AuthoredSource =
        """
        namespace Marten
        {
            public interface IDocumentStore;
            public interface IDocumentSession
            {
                void Store<T>(T document);
            }
        }

        namespace Alpha
        {
            public sealed class Payload;
        }

        namespace Beta
        {
            public sealed class Payload;
        }

        namespace IdentitySamples
        {
            public sealed class Outer<T>
            {
                public sealed class Nested<TValue>;
            }

            public sealed class IdentityDocument;

            public static partial class Handler
            {
                public static void Same(Alpha.Payload value, Marten.IDocumentSession session) => session.Store(value);
                public static void Same(Beta.Payload value, Marten.IDocumentSession session) => session.Store(value);
                public static void Combine(Alpha.Payload first, Beta.Payload second, string label, Marten.IDocumentSession session) => session.Store(first);
                public static void Modifiers(ref int byRef, in long byIn, out short byOut, ref readonly decimal byRefReadonly, Marten.IDocumentSession session, params string[] values)
                {
                    byOut = 0;
                    session.Store(new IdentityDocument());
                }
                public static void Generic<TFirst, TSecond>(TFirst first, TSecond second, Marten.IDocumentSession session) => session.Store(new IdentityDocument());
                public static void Shapes(Outer<Alpha.Payload>.Nested<Beta.Payload>[] values, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<Alpha.Payload[,]>> map, Marten.IDocumentSession session) => session.Store(new IdentityDocument());
            }
        }
        """;

    const string GeneratedSource =
        """
        // <auto-generated/>
        namespace IdentitySamples;

        public static partial class Handler
        {
            public static void Same(Alpha.Payload value, int generated, Marten.IDocumentSession session) => session.Store(value);
            public static void Generic<T>(T value, Marten.IDocumentSession session) => session.Store(value);
        }
        """;

    static readonly IReadOnlyList<MetadataReference> _references =
    [
        .. ((string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!)
            .Split(Path.PathSeparator)
            .Select(_ => MetadataReference.CreateFromFile(_))
    ];

    protected DotNetProjectCompilation Project = null!;
    protected INamedTypeSymbol HandlerType = null!;

    void Establish()
    {
        var authoredTree = CSharpSyntaxTree.ParseText(AuthoredSource, path: "/workspace/IdentitySamples/Handlers.cs");
        var generatedTree = CSharpSyntaxTree.ParseText(GeneratedSource, path: "/workspace/IdentitySamples/Handler.g.cs");
        var compilation = CSharpCompilation.Create(
            "IdentitySamples",
            [authoredTree, generatedTree],
            _references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, nullableContextOptions: NullableContextOptions.Enable));
        Project = new DotNetProjectCompilation
        {
            Name = "IdentitySamples",
            ProjectPath = "/workspace/IdentitySamples/IdentitySamples.csproj",
            SourceRoot = "/workspace",
            Compilation = compilation,
            AuthoredSyntaxTrees = new HashSet<SyntaxTree> { authoredTree }
        };
        HandlerType = compilation.GetTypeByMetadataName("IdentitySamples.Handler")!;
    }
}
