// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.CritterStack.Screenplay.given;

public class a_generated_source_only_wolverine_saga_application : Specification
{
    const string FrameworkSource =
        """
        namespace Wolverine
        {
            public class WolverineOptions;
        }

        namespace JasperFx.Events
        {
            public interface IEventStream<T>
            {
                T? Aggregate { get; }
                void AppendOne(object @event);
            }
        }
        """;

    const string ApplicationSource =
        """
        namespace Orders;

        public record BeginAdversarialSaga(System.Guid Id);
        public record ContinueAdversarialSaga(System.Guid Id);
        public record ReturnGeneratedCanonicalMessage(System.Guid Id);
        public record AppendGeneratedCanonicalEvent(System.Guid Id);
        public sealed class Order;

        public sealed class AdversarialSaga : Wolverine.Saga
        {
            public static AdversarialSaga Start(BeginAdversarialSaga message) => new();
            public void Handle(ContinueAdversarialSaga message) { }
        }

        public sealed class GeneratedCanonicalMessage : Wolverine.Saga;
        public sealed class GeneratedCanonicalEvent : Wolverine.Saga;

        public static class OrdinaryHandler
        {
            public static GeneratedCanonicalMessage Handle(ReturnGeneratedCanonicalMessage message) => new();

            public static void Handle(
                AppendGeneratedCanonicalEvent message,
                JasperFx.Events.IEventStream<Order> stream) => stream.AppendOne(new GeneratedCanonicalEvent());
        }
        """;

    const string GeneratedFrameworkSource =
        """
        // <auto-generated/>
        namespace Wolverine
        {
            public abstract class Saga;
        }
        """;

    static readonly IReadOnlyList<MetadataReference> _references =
    [
        .. ((string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!)
            .Split(Path.PathSeparator)
            .Select(_ => MetadataReference.CreateFromFile(_))
    ];

    protected DotNetProjectCompilation Project = null!;

    void Establish() => Project = CreateProject();

    internal static DotNetProjectCompilation CreateProject()
    {
        var frameworkTree = CSharpSyntaxTree.ParseText(FrameworkSource, path: "/workspace/Framework.cs");
        var applicationTree = CSharpSyntaxTree.ParseText(ApplicationSource, path: "/workspace/Orders/Handlers.cs");
        var generatedFrameworkTree = CSharpSyntaxTree.ParseText(GeneratedFrameworkSource, path: "/workspace/Generated/Wolverine.g.cs");
        var compilation = CSharpCompilation.Create(
            "Orders",
            [frameworkTree, applicationTree, generatedFrameworkTree],
            _references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, nullableContextOptions: NullableContextOptions.Enable));
        return new DotNetProjectCompilation
        {
            Name = "Orders",
            ProjectPath = "/workspace/Orders/Orders.csproj",
            SourceRoot = "/workspace",
            Compilation = compilation,
            AuthoredSyntaxTrees = new HashSet<SyntaxTree> { frameworkTree, applicationTree }
        };
    }
}
