// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Cratis.CritterStack.Screenplay.for_CritterStackSource;

public class when_referenced_declarations_are_generated : given.a_critter_stack_source_context
{
    Evidence _generatedNameEvidence = null!;
    Evidence _generatedHeaderEvidence = null!;
    SourceRange? _generatedLocationRange;
    SourceRange? _outOfContextLocationRange;

    void Because()
    {
        var generatedNameTree = SourceTree(
            "namespace Referenced; public sealed class GeneratedName;",
            "/checkout/Referenced/GeneratedName.g.cs");
        var generatedHeaderTree = SourceTree(
            "// <auto-generated/>\nnamespace Referenced; public sealed class GeneratedHeader;",
            "/checkout/Referenced/GeneratedHeader.cs");
        var authoredReferenceTree = SourceTree(
            "namespace Referenced; public sealed class AuthoredReference;",
            "/checkout/Referenced/AuthoredReference.cs");
        var referencedCompilation = SourceCompilation(
            "Referenced",
            [generatedNameTree, generatedHeaderTree, authoredReferenceTree]);
        var project = ReferencingProject(
            referencedCompilation,
            "/checkout",
            additionalAuthoredTrees: [generatedNameTree]);

        _generatedNameEvidence = EvidenceFor(ReferencedType(project, "Referenced.GeneratedName"), project);
        _generatedHeaderEvidence = EvidenceFor(ReferencedType(project, "Referenced.GeneratedHeader"), project);
        _generatedLocationRange = RangeForProject(generatedNameTree.GetRoot().GetLocation(), project);
        _outOfContextLocationRange = RangeForProject(authoredReferenceTree.GetRoot().GetLocation(), project);
    }

    [Fact] void should_not_use_a_generated_file_name_as_authored_evidence() => _generatedNameEvidence.Source.ShouldBeNull();
    [Fact] void should_not_use_a_generated_header_as_authored_evidence() => _generatedHeaderEvidence.Source.ShouldBeNull();
    [Fact] void should_reject_a_generated_location_even_if_the_host_admitted_its_tree() => _generatedLocationRange.ShouldBeNull();
    [Fact] void should_keep_location_ranges_strictly_within_the_host_authored_context() => _outOfContextLocationRange.ShouldBeNull();
}
